### ISSUE TITLE
EsriGridReader could not read z values ?

### ISSUE THREAD

**Issue by leminhson** [OpenGeoVis/PVGeo#108]
**Describe the bug**
**EsriGridReader** works well with **PyVista 0.28**, but it is not the case with **PyVista 0.38** !
Now EsriGridReader returns a UniformGrid with all z-values being zeros (0) _(see screenshot below)_
Maybe this issue is due to something changed in PyVista ?

**Screenshot**
![EsriGridReader_error](https://user-images.githubusercontent.com/14102005/234578632-f6ec901e-436c-4834-a6e0-6d639be3bc3f.png)

**Here is a data file:**
ncols 5
nrows 9
xllcenter 0
yllcenter 0
cellsize 100.00
nodata_value  -9999
10 20 30 40 50
20 30 40 50 60
30 40 50 60 70
40 50 60 70 80
50 60 70 80 90
60 70 80 90 100
70 80 90 100 110
80 90 100 110 120
90 100 110 120 130

**Desktop :**
 - OS: Windows 11
 - Python 3.11.0
 - PyVista 0.38
 - PVGeo 2.1

**Comment by banesullivan** [comment]
Would you also please share a Report:

```py
import pyvista as pv
print(pv.Report())
```

**Comment by banesullivan** [comment]
I'm confused what the issue is. The Z-values should be zero for this mesh. It defines an 5x9 XY grid with no Z component. If I use PyVista 0.28, I get the same result as the the latest PyVista.

I think you just want to use the data values on that grid to warp the z-component like in this example: https://pvgeo.org/examples/grids/read-esri.html#sphx-glr-examples-grids-read-esri-py

```py
# %%

from PVGeo.grids import EsriGridReader


file_path = 'test.grd'
dem = EsriGridReader().apply(file_path)
dem

# %%

surface = dem.warp_by_scalar()
surface.plot(show_grid=True)
# %%

```

![image](https://user-images.githubusercontent.com/22067021/234621579-d6e97b74-94df-45b9-bda6-92062f5ee827.png)

**Comment by leminhson** [comment]
> I think you just want to use the data values on that grid to warp the z-component

@banesullivan : That is exactly what I want. But when I apply _warp_by_scalar()_, it shows an error.

But now PyVista and PVGeo work well without any error !!! I do not know what had happened last time
