### ISSUE TITLE
Export slice to external grid format

### ISSUE THREAD

**Issue by craigmillernz** [OpenGeoVis/PVGeo#16]
I'd like to be able to export the slice from `ManySlicesAlongAxis` to an external grid format, such as surfer ascii format.  This will help with creating publication quality plots (often tricky with paraview ).

The format of the Surfer ASCII grid format is as follows:  There is also a binary format

```
DSAA
NumberOfColumns NumberOfRows
MinXCoordinate MaxXCoordinate
MinYCoordinate MaxYCoordinate
MinZValue MaxZValue
####.### ####.### ####.###...
####.### ####.### ####.###...
```

An Example is given below:

```
DSAA
201 380
416798.95 417000
4679619.71 4680000
174.66 174.54 174.39 ...
175.44 174.32 173.99 ...
```

Here's a code snippet that uses SimPEG to extract a slice from a model (mesh.r is a simpeg tensor mesh function) and write it in surfer ascii format.  

```py
model[~actind] = 1.71041e38 #surfer no data value #actind are active cells defined elsewhere
slice_data = mesh.r(model, 'CC', 'CC','M')[:,:,indz]  # this extracts the slice in the correct order for surfer

Nx = mesh.nCx # number cells x dir
Ny = mesh.nCy # number cells y dir
Xmin = mesh.x0[0]  #mesh.x0 is the origin
Xmax = mesh.x0[0] + mesh.hx[0]*mesh.nCx
Ymin = mesh.x0[1]
Ymax = mesh.x0[1] + mesh.hy[1]*(mesh.nCy -1) + mesh.hy[-1]
valmin = slice_data.min()
valmax = slice_data[slice_data != 1.71041e38].max()


#swap rows and columns for surfer
slice_data = slice_data.T
#write surfer header
header='\n'.join(['DSAA', str(Nx) + ' ' + str(Ny), str(Xmin) + ' ' + str(Xmax), str(Ymin) + ' ' + str(Ymax),  str(valmin) + ' ' + str(valmax)])
#save file
np.savetxt(outdir + 'elevation_' + str(layer) + '.grd', slice_data, header=header, comments='')

```

**Comment by banesullivan** [comment]
Hi @craigmillernz, I think this functionality will totally be possible to develop. I just want to clarify what you would want to export. In [**this video**](https://vimeo.com/282010041), I have demonstrated the `ManySlicesAlongAxisFilter` and what it produces. 


I see a few options for what we could save out and I'm curious which would be most desired:
- Save all of the slices out to their own file? 
- Use the slices as a sparse tensor mesh in a sense? 
- Just save a single one of the slices?

**Comment by craigmillernz** [comment]
Hi 
Thanks for the video!  That slicing looks slick! 

**1. Save all of the slices out to their own file?**

Yes with one file per slice.  The slices exported would match the "number of slices" selected


**2. Use all of the slices as one sparse tensor mesh in a sense? (only possible for certain input types)**
Not sure what you mean here?

**3. Just save a single one of the slices?**
If number of slices =1 then it would just save that slice, but it would be good to be able to choose the location of that slice.  If a user wanted a particular slice along a certain easting/northing/depth can that be done?

**Comment by banesullivan** [comment]
Great, I will implement a GUI button of some sort to save each slice to their own file for the `ManySlicesAlongAxis` filter. I will also create a writer that will handle slices created from ParaView's *Slice* filter so that a user can place the one slice wherever they like and save that to a surfer grid.

I want to make sure I have a clear understanding of the Surfer format: When saving a 2D slice to the surfer format,
1. would the "*Z*-values" be the attribute of the sliced data object? (what it is colored by e.g. conductivity)
2. Can these grids only be defined on an XY-plane?

*Note: I will also implement a reader for the Surfer grid format*

> An option to set the spacing of the slices, (instead of the number) would be useful. Like slice every 100m. I guess this would be achievable with the "number of slices". Maybe displaying the slice spacing alongside the number of slices would be useful

Good suggestion, I'll see what I can implement to make this possible!

**Comment by craigmillernz** [comment]
1.  would the "Z-values" be the attribute of the sliced data object? (what it is colored by e.g. conductivity)
Yes.
        2.Can these grids only be defined on an XY-plane?
In theory I think you could define them on any plan, but you’d need to define the xmin/xmax, i.e. the “left to right” extent of the section.  This means that for a diagonal section close to one of the X or Y axis you might end up with scaling problems.  It would be easier perhaps to restrict them to the X or Y planes.

**Comment by banesullivan** [comment]
I have implemented a Surfer ASCII grid reader/writer combo for `vtkImageData` (uniform rectilinear grid) that will be included in my next merge request.

Since the surfer grid is essentially just an image (a *uniformly* spaced 2D grid) I am having an issue when trying to extract a slice from a *non-uniform* grid (say a rectilinear or octree grid). This means the Surfer format writer would have to resample the input dataset to a uniform grid across the data extents.

... This can be done ... however, I'm not sure I think it is a safe operation to perform as it would effectively be interpolating the input dataset to a higher resolution.

For example: In the picture below, I created a 2D rectilinear grid with non-uniform cell spacing. The resulting Surfer grid would have to resample that data to the **black points** shown atop that dataset. 

![surfer-issue](https://user-images.githubusercontent.com/22067021/43731566-23b6ac20-996c-11e8-8f5a-ebc21c534bff.png)


I'm concerned that this type of resampling would harm the input dataset's integrity and I'm not sure about implementing it. What are your thoughts @craigmillernz? Is there another grid format for Surfer, or that Surfer can read, that handles *non-uniform* grids?

As a workaround, I can go ahead and implement the XYZ (`.csv`) writer for the points/data of the slices resulting from `ManySlicesAlongAxis` which I assume Surfer can handle importing?

**Comment by craigmillernz** [comment]
Good point.  Simpeg has a plot slice function for octree, that might be worth looking at.
I think they interpolate back to the Tensor mesh.
https://github.com/simpeg/discretize/blob/master/discretize/TreeMesh.py plotSlice.

The other option as you suggest would be to export as a csv or (x,y, value) and then use an external program (surfer) to regrid and plot.

**Comment by banesullivan** [comment]
I've been slow to get around to this but I have implemented one solution to this feature request in #21 .

First, I changed up how the slicing filters produce an output on the backend (using composite datasets rather than appended unstructured grids) to allow us to have data structures that could be saved out separately. Then I added a new filter `PVGeo.filters.ExtractCellCenters` (ParaView's native Cell Centers filter wasn't working for this) that will create XYZ+atts data of the cell centers for any input dataset's cell data. If you use this filter on your sliced dataset (e.g. from `PVGeo.filters.ManySlicesAlongAxis`) then you can use ParaView's native CSV writer to save out the XYZ+atts data for each slice individually for use in Surfer or other programs while preserving resolution somewhat well.

It's important to keep track of what attributes you are looking at in ParaView (cells vs. points). If your sliced dataset only contains PointData then just go ahead and save the slices use ParaView's CSV writer. However, if you would like to save the cell data (what we use in the UBC grids) then you must follow the process above which I demonstrate in [this lengthy video](https://vimeo.com/286429857).

To tell apart Cell data from Point data, ParaView uses a convenient graphic when selecting display attribute where a point looking diamond thing denotes points and a cube/voxel represents cell data like shown in the following screen capture:

<img width="643" alt="screen shot 2018-08-23 at 3 51 52 pm" src="https://user-images.githubusercontent.com/22067021/44554000-98bfcf00-a6ec-11e8-8f31-fca338a4b918.png">
