### ISSUE TITLE
Edit Axis Ticks and Labels

### ISSUE THREAD

**Issue by jacobgrasmick** [OpenGeoVis/PVGeo#2]
How can I rotate the axis label of a specific axis? (e.g. the vertical/elevation axis label)

**Comment by banesullivan** [comment]
Unfortunately, to have the labels be parallel to their axis is not currently possible in ParaView (*to my knowledge*). I will keep this in mind and update this if anything changes.

**Comment by banesullivan** [comment]
From PVGP user over email:

> I want to reduce the number of ticks on the Easting (x-axis) so the tick labels are not overlapping.
> Do you know how to do this?

**Comment by banesullivan** [comment]
Axis tick marks can be tricky… This can be due to the number of axis ticks specified or the screen/picture resolution. 

## Specify the Axis Ticks

### Through the Python Shell
One of the easier ways to set the axis ticks is to use Python ranges through the PVPython shell. Open up the Python shell **View->Python Shell** (or **Tools->Python Shell** depending on your ParaView version) and execute code similar to (this is for the Y-axis):

```py
# Get the Active View: note this only edits the axis in that view
rv = GetActiveViewOrCreate('RenderView')

# Edit the Properties of the AxesGrid
rv.AxesGrid.YAxisUseCustomLabels = 1    # 1 means true
# note that third parameter is the step size for `range`
rv.AxesGrid.YAxisLabels = range(0,3000,1000)
# you may need to move the render view around for it to update or execute:
RenderAllViews()
```

### Through the GUI
Click on the **Built-In** source in the pipeline view.

Click the big **Edit** button next to **Axes Grid**. Click the *Gear Icon* at the top to enable the Advanced properties.

Scroll down to **Y Axis Label Properties**.  Check the **Use Custom Labels** box and add values you’d like to label. See below image for an example:

<img width="678" alt="axis_ticks" src="https://user-images.githubusercontent.com/22067021/40446297-fe30c848-5e8b-11e8-899e-ea92a4a93488.png">

## Picture Resolution
Another quick fix is to up the resolution when you save the screenshot.

**File -> Save Screenshot**:
In the popup window, there is a black X next to the image dimensions. Try multiplying by 2 once or twice or three times even.

This will maintain the number of ticks but as the resolution goes up the labels should stop overlapping. 

![resolution](https://user-images.githubusercontent.com/22067021/40446751-833f69c6-5e8d-11e8-9903-093bde1eead6.png)
