### ISSUE TITLE
Specify compatible Python versions

### ISSUE THREAD

**Issue by leouieda** [OpenGeoVis/PVGeo#41]
It would be useful to have the compatible Python versions listed somewhere. I see a mention to Python 3.x in the README but it would be best to know which ones exactly. I'd recommend committing to support 3.6+ only since conda-forge no longer builds 3.5 packages.

In particular, it would be good to specify the `python_requires` argument to `setup.py` so that pip knows which versions are compatible.

**Comment by banesullivan** [comment]
I'll update the docs to explicitly say which versions of Python are supported. 

> I'd recommend committing to support 3.6+ only since conda-forge no longer builds 3.5 packages.

Thanks, I think that's a fair limit on Python 3.x support. PVGeo will, however, continue full support for Python 2.7 until ParaView switches to Python 3.7 (likely on release `5.8` next fall). 

Most users of PVGeo will hopefully be transitioning to using `vtki` (which we are working towards only supporting 3.6+) rather than ParaView for the supporting visualization package. The wrappings that make PVGeo available as plugins directly within ParaView is a major selling point to many users - thus Python 2.7 will have to remain for this project.

**Comment by banesullivan** [comment]
@leouieda: I implemented changes to address this, but would you please close this issue when you think these points are resolved?

**Comment by leouieda** [comment]
:+1: looks good to me
