### ISSUE TITLE
examples 

### ISSUE THREAD

**Issue by alexgarciac** [OpenGeoVis/PVGeo#47]
hi is there a jupiter notebook for this? if not then is there sample data so that all the features described in your joss submission can be made part of a jupiter?

**Comment by banesullivan** [comment]
Hi @alexgarciac! Thank you for bringing this and https://github.com/openjournals/joss-reviews/issues/1384#issuecomment-492868977 to my attention.

Relevant to https://github.com/openjournals/joss-reviews/issues/1451

In a few recent commits (as a first pass at a solution to this issue), I added a deployment script that sends all of the [example notebooks that are automatically generated in our documentation](https://pvgeo.org/examples/index.html) to a [separate repository](https://github.com/OpenGeoVis/pvgeo-binder) that can be launched on [MyBinder](https://mybinder.org) by anyone with an internet connection. Please feel free to test out some of PVGeo's functionality there!

Launch the examples here: [![Launch on MyBinder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/OpenGeoVis/pvgeo-binder/master)

In these examples, we download sample data on the fly much like how we do in [PyVista's examples](https://docs.pyvista.org/examples/index.html) from [a separate data repository](https://github.com/pyvista/vtk-data) and other external weblinks because it is not sustainable for us to host too many data files along side the source code.

Also, one of our biggest challenges with PVGeo has been finding open-access data files that we can use to demonstrate PVGeo's capabilities - IMHO this will be a struggle throughout the life of most open-source geoscience software, let alone PVGeo.
