### ISSUE TITLE
Dataset can only by warped by a point data array.

### ISSUE THREAD

**Issue by huyquangtranaus** [OpenGeoVis/PVGeo#62]
Hi,

Could you please help figure what caused the error message below?

Thanks    

warped = dem.warp_by_scalar(scale_factor=300.)

  File "C:\Users\User\anaconda3\lib\site-packages\pyvista\core\filters.py", line 1135, in warp_by_scalar
    raise TypeError('Dataset can only by warped by a point data array.')

TypeError: Dataset can only by warped by a point data array.

**Comment by banesullivan** [comment]
Hi this isn’t a PVGeo issue but a PyVista topic. I’d recommend heading to this forum next time: https://github.com/pyvista/pyvista-support

But to answer your question, the error message is pretty telling. The `warp_by_scalar` filter in PyVista can only warp by point data. You must have cell data. Try running `.cell_data_to_point_data()` first. E.g.:

```py
warped = dem.cell_data_to_point_data().warp_by_scalar(scale_factor=300.)
```

Or because that method is so common, we’ve aliased it:


```py
warped = dem.ctp().warp_by_scalar(scale_factor=300.)
```

I’d recommend reading the docs for PyVista to understand the data structures you are working with: https://docs.pyvista.org/getting-started/what-is-a-mesh.html

**Comment by banesullivan** [comment]
Specifically, this is the filter you are using: https://docs.pyvista.org/core/filters.html#pyvista.DataSetFilters.warp_by_scalar
